### ISSUE TITLE
Error in log when checking new version of HA

### ISSUE THREAD

**Issue by PerVildstrand** [TekniskSupport/home-assistant-sjoverket#1]
Hi!

When I run the "Check Home Assistant configuration community plugin", I get the following error in the plugin log:

_Failed config
  General Errors: 
    - Platform error sensor.sjofartsverket - No module named 'jsonpath'_

When I deactivate the lines in sensor.yaml the check runs without errors.

/Per

**Comment by TekniskSupport** [comment]
Hi,

I'm running 0.111.4 with no issues, not really sure why it's complaining about missing python modules i got multiple errors in the log when i checked my configuration with the addon, but all of them work and produced no errors in my real installation log.

```
[16:40:20] INFO: Installing Home Assistant: latest...
[16:40:20] INFO: Please be patient, this might take a few minutes...
[16:41:10] INFO: Installed Home Assistant 0.111.4
[16:41:10] INFO: Making a copy of your configuration for checking...
[16:41:10] INFO: Checking your configuration against this version...
[16:44:51] ERROR: The configuration check did not pass!
[16:44:51] ERROR: See the output below for more details.
Testing configuration at /tmp/config
Failed config
  General Errors: 
    - Component error: sia - No module named 'sseclient'
    - Platform error sensor.sjofartsverket - No module named 'jsonpath'
    - Platform error sensor.krisinformation - No module named 'xmltodict'

Successful config (partial)
[16:44:51] INFO: The full output has been written to /share/check_config.txt
```

I can take a look at it and see if i can exchange the json module but right now i think that the addon is broken is more likely

//iesus

**Comment by TekniskSupport** [comment]
I solved it by updating the manifest.json, to load the component after rest is loaded

**Comment by PerVildstrand** [comment]
Thanks, working now.

**Comment by TekniskSupport** [comment]
No problem, sorry for the delay, I totally missed the notification
