### ISSUE TITLE
Home assistant Problem med "kort" webbsida

### ISSUE THREAD

**Issue by Sandvikskammen** [TekniskSupport/home-assistant-sjoverket#3]
Hej!
Försöker lägga till en hemsida i kortet webbsida. Se bifogade bilder. Står att _"hemsidan avvisade anslutningen"_. Lyckades med Viva men inte Skellefteå kommun, www.sjoraddning.se/vader, eller https://www.vackertvader.se/v%C3%A4derstation/bjur%C3%B6klubb. Provade även i appen på min Iphone vilket inte heller fungerade. Tacksam för hjälp//Sonny

![image](https://user-images.githubusercontent.com/96996741/147887462-64c44916-dfea-42d6-a991-3bb4a133e131.png)
![image](https://user-images.githubusercontent.com/96996741/147887479-73617af0-c782-4d4b-b626-0c7ef668d77f.png)

**Comment by TekniskSupport** [comment]
Hej Sonny,

Sorry jag missförstod nog dig på forumet, Jag trodde att du försökte använda sjöfartsverketsintegrationen

Men hur ser det ut i loggen från webbläsaren?
(nätverksloggen)

Vänligen Iesus

**Comment by Sandvikskammen** [comment]
![image](https://user-images.githubusercontent.com/96996741/147888002-f1f30d34-9527-493c-8944-0ca522c8592d.png)
 kan det vara detta du tänker på. Ursäkta en amatör//Sonny

**Comment by TekniskSupport** [comment]
Det var precis det jag var ute efter,

Tyvärr så visar meddelandet på att det kan vara lite svårt att gå runt, det är en säkerhetsfunktion som man kan som sajtägare välja att implementera så att det blir svårare att embeda sidan i en annan 

Däremot kan man (oftast) scrapea av information av sajten, eller nyttja någon form av API för att få informationen
 
 Går att läsa mer om den headerflaggan här:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

**Comment by Sandvikskammen** [comment]
Tack!
Tråkigt, tänker jag ska kontakta berörda och höra hur de tänker och om de kan tänka sig fundera om. Funktionen var supersmidig för en amatör som mig. Tacksam för att Sjöfartsverket inte valt den funktionen. Bor hyfsat nära Gåsören och Bjuröklubb så det är intressant och värdefullt att kunna läsa data på ett enkelt sätt. Supertack för hjälpen//Sonny

**Comment by TekniskSupport** [comment]
Sjöfartsverket har ett öppet API som vi får använda istället
Du kan installera integrationen via HACS, så får du in sensorer av informationen :) 

https://github.com/TekniskSupport/home-assistant-sjofartsverket/blob/master/info.md
