### ISSUE TITLE
Added sensors

### ISSUE THREAD

**Issue by mnor2** [TekniskSupport/home-assistant-sjoverket#4]
It should be highly appreciated to be able to get additional values apart from wind. For example Vattenstånd and Vattentemp, found on station 69 and byvind as found on station 182. also the wind direction for medelvind and byvind would be nice, either as the stated N-NV-V etc or the heading in degrees.

**Comment by TekniskSupport** [comment]
I'll have a look at it on that perticular station, but it should already add sensors for those measurements
 
![image](https://user-images.githubusercontent.com/13868526/152235895-c3c5ed9e-6612-4cd6-93e3-2d622335dcd0.png)
![image](https://user-images.githubusercontent.com/13868526/152235789-35d42058-6982-4da8-b3d6-ba1ee5c9c90b.png)
![image](https://user-images.githubusercontent.com/13868526/152235844-75e8a67b-f3d7-4d5a-b827-fceb1890acb5.png)

**Comment by mnor2** [comment]
Sorry, yes the sensors are there but the measurement is not a numerical value for the vind or byvind

**Comment by TekniskSupport** [comment]
Oh, i have been reluctant to manipulate the data from the API, but i could do a trade of try to add it as attributes
would that suffice?

**Comment by mnor2** [comment]
I suppose so, cause it makes more sense to have the measurements as a value instead of a text string, both for presentation and statistics.

**Comment by TekniskSupport** [comment]
I agree. thou at this time i only display what is returned from the API

The reason why I have been reluctant to manipulate the data is that it could break if they change things up, even within the specs of their API,  And at this point it would be a breaking change.

Preferably ViVa should change what their data is returning, have sensordata in different fields. 

An even better solution may be to have an option/setting making the sensor split the data, if it breaks you can always return it to display the data as it is retreived

**Comment by TekniskSupport** [comment]
Added numeric_values to configuration, will force the sensor values into numeric
